"""Initial migration.

Revision ID: 14aa9404c415
Revises:
Create Date: 2025-07-14 13:04:18.283541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14aa9404c415'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('planner_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('subject1_id', sa.Integer(), nullable=False),
    sa.Column('material1', sa.String(length=100), nullable=True),
    sa.Column('subject2_id', sa.Integer(), nullable=False),
    sa.Column('material2', sa.String(length=100), nullable=True),
    sa.Column('learning_subject_id', sa.Integer(), nullable=False),
    sa.Column('learning_task', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['learning_subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['subject1_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['subject2_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'week_start', name='_day_week_uc')
    )
    with op.batch_alter_table('planner_entry', schema=None) as batch_op:
        batch_op.create_index('idx_day', ['day'], unique=False)
        batch_op.create_index('idx_week_start', ['week_start'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planner_entry', schema=None) as batch_op:
        batch_op.drop_index('idx_week_start')
        batch_op.drop_index('idx_day')

    op.drop_table('planner_entry')
    op.drop_table('subject')
    # ### end Alembic commands ###
