"""add order column to Task

Revision ID: 23538eb60ee0
Revises: 4122faa86cf1
Create Date: 2025-08-11 10:26:01.893021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23538eb60ee0'
down_revision = '4122faa86cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('order', sa.Integer(), nullable=True, server_default='0')
        )

    # Set a default order for existing rows
    task_table = sa.table('task', sa.column('order', sa.Integer()))
    op.execute(
        task_table.update().values(order=0).where(task_table.c.order.is_(None))
    )

    # Now make the column non-nullable
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('order', existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
