"""Add Task model

Revision ID: 4122faa86cf1
Revises: 14aa9404c415
Create Date: 2025-07-16 10:26:44.541928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4122faa86cf1'
down_revision = '14aa9404c415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """
    Führt die Migration aus, indem die Tabelle `task` mit den entsprechenden Spalten erstellt wird.
    """
    op.create_table('task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """
    Entfernt die Tabelle `task` aus der Datenbank, um die Migration rückgängig zu machen.
    """
    op.drop_table('task')
    # ### end Alembic commands ###
