"""Update task model with enums, due_date, and integer id

Revision ID: 98872ae14561
Revises: 23538eb60ee0
Create Date: 2025-08-11 21:24:01.101539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98872ae14561'
down_revision = '23538eb60ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
               nullable=False)
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'),
               nullable=False)
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.DATETIME(), nullable=True))
        batch_op.alter_column('priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('due_date')
    # Add new integer column for primary key
    op.add_column('task', sa.Column('new_id', sa.Integer(), primary_key=True, autoincrement=True))

    # Populate new_id for all existing rows
    # (Autoincrement will handle this automatically for new rows, but for existing rows, we need to fill it)
    # SQLite and some DBs will auto-populate, but for safety, we ensure all rows have a value
    # No action needed if DB supports autoincrement on nullable columns, otherwise use raw SQL if needed

    # Add new columns
    op.add_column('task', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('task', sa.Column('updated_at', sa.DateTime(), nullable=False))

    # Change status and priority columns to enums
    op.alter_column('task', 'status',
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
        nullable=False)
    op.alter_column('task', 'priority',
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'),
        nullable=False)

    # Drop old columns
    op.drop_column('task', 'start_time')
    op.drop_column('task', 'end_time')

    # Drop old primary key constraint if necessary (depends on DB)
    # Remove old id column
    op.drop_constraint('task_pkey', 'task', type_='primary')
    op.drop_column('task', 'id')

    # Rename new_id to id
    op.alter_column('task', 'new_id', new_column_name='id', existing_type=sa.Integer(), primary_key=True)

    # Recreate primary key constraint
    op.create_primary_key('task_pkey', 'task', ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back old id column as VARCHAR(36)
    op.add_column('task', sa.Column('old_id', sa.VARCHAR(length=36), nullable=True))

    # If you have a backup of the old UUIDs, you could restore them here.
    # Otherwise, this will leave old_id NULL for all rows.

    # Drop new integer PK constraint and column
    op.drop_constraint('task_pkey', 'task', type_='primary')
    op.alter_column('task', 'id', new_column_name='new_id', existing_type=sa.Integer())
    op.drop_column('task', 'new_id')

    # Rename old_id back to id
    op.alter_column('task', 'old_id', new_column_name='id', existing_type=sa.VARCHAR(length=36))
    op.create_primary_key('task_pkey', 'task', ['id'])

    # Add back dropped columns
    op.add_column('task', sa.Column('end_time', sa.DATETIME(), nullable=True))
    op.add_column('task', sa.Column('start_time', sa.DATETIME(), nullable=True))

    # Change enums back to VARCHAR
    op.alter_column('task', 'priority',
        existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'),
        type_=sa.VARCHAR(length=20),
        nullable=True)
    op.alter_column('task', 'status',
        existing_type=sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
        type_=sa.VARCHAR(length=20),
        nullable=True)

    # Drop new columns
    op.drop_column('task', 'updated_at')
    op.drop_column('task', 'created_at')
    op.drop_column('task', 'due_date')
    # ### end Alembic commands ###
